// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package number

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NumberClient is the client API for Number service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumberClient interface {
	GetRandomNumber(ctx context.Context, in *GetRandomNumberRequest, opts ...grpc.CallOption) (*GetRandomNumberResponse, error)
}

type numberClient struct {
	cc grpc.ClientConnInterface
}

func NewNumberClient(cc grpc.ClientConnInterface) NumberClient {
	return &numberClient{cc}
}

func (c *numberClient) GetRandomNumber(ctx context.Context, in *GetRandomNumberRequest, opts ...grpc.CallOption) (*GetRandomNumberResponse, error) {
	out := new(GetRandomNumberResponse)
	err := c.cc.Invoke(ctx, "/Number/GetRandomNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumberServer is the server API for Number service.
// All implementations should embed UnimplementedNumberServer
// for forward compatibility
type NumberServer interface {
	GetRandomNumber(context.Context, *GetRandomNumberRequest) (*GetRandomNumberResponse, error)
}

// UnimplementedNumberServer should be embedded to have forward compatible implementations.
type UnimplementedNumberServer struct {
}

func (UnimplementedNumberServer) GetRandomNumber(context.Context, *GetRandomNumberRequest) (*GetRandomNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomNumber not implemented")
}

// UnsafeNumberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumberServer will
// result in compilation errors.
type UnsafeNumberServer interface {
	mustEmbedUnimplementedNumberServer()
}

func RegisterNumberServer(s grpc.ServiceRegistrar, srv NumberServer) {
	s.RegisterService(&Number_ServiceDesc, srv)
}

func _Number_GetRandomNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberServer).GetRandomNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Number/GetRandomNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberServer).GetRandomNumber(ctx, req.(*GetRandomNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Number_ServiceDesc is the grpc.ServiceDesc for Number service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Number_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Number",
	HandlerType: (*NumberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomNumber",
			Handler:    _Number_GetRandomNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/number.proto",
}
